### ISSUE TITLE
New version of Electric Drummer

### ISSUE THREAD

**Issue by scripting** [scripting/drummerSupport#111]
Does it work?

**Comment by kantel** [comment]
I installed it on my Mac and it seems that is it running fine, But the link to the change note above doesn't work so I can't test the new stuff. 🤓

**Comment by scripting** [comment]
@kantel -- you're right -- but it doesn't say what changed. basically everything in the change notes outline since Oct 10, the last time E/D was built.

**Comment by kantel** [comment]
@scripting Okay , let me have time during this weekend. After my stroke I have such a lot to organize my RSS feeds for my future blogposts and i want to use (Electric) Drummer for it (I think it's the right tool for that). Latest on Monday I can tell you what works fine and what should need a refurbish, I think.

But keep in mind at the moment I use Drummer only a the surface. For deeper exploration (i.g. scripting) I still have to learn a lot.

By the way (just for curiosity): Which tool are you using vor translating OPML files to Markdown files?

And it it's on both sides: I'm glad to be working with you, too.

**Comment by scripting** [comment]
@kantel -- I'm just starting to think about what I want to do re generating Markdown from outlines. 

I have a lot of possible approaches, and I do it in Frontier which is how I currently write my docs and readme's for GitHub. 

First I had to get the foundation into Drummer with the github.xxx verbs, now they're in, there are a lot of choices. ;-)

**Comment by papascott** [comment]
Did a quick test of GitHub, I was able to get the GitHub token from Web Drummer into Electric Drummer, and github.getUserInfo () in Electric Drummer succeeded. Nice to know how to read and write from localStorage from Drummer! 😄

**Comment by gwthompson** [comment]
@scripting I just updated my E/D and it seems all of my root scripts are now returning an error like this:

Error running script: root.hello is not a function.

All of my scripts were working before the upgrade but now they all return the same error with only change being the name of my function.

What can I do to help determine if this is a new version issue or my local issue?

**Comment by scripting** [comment]
@gwthompson — if you address your question to me then other people are less likely to help. I’m sure there are other people who could suggest more info you need to provide to figure out what’s going wrong.

**Comment by gwthompson** [comment]
I removed all of my scripts from root and then added them back in one at a time testing them as I went along. I finally got to a script that caused all of my scripts to return the "not a function" error. I had not been working on my scripts this week due to another obligation so I must have introduced the error at the end of last week when I was adding in new features. The confusing part was all of the scripts would trigger an error even though only one script actually had an error.

I corrected the error and now all of the scripts are working once again. 

Back to adding new features for my Obsidian integration! 😀

**Comment by mistersugar** [comment]
E/D v.2.0.11 on my new MacBook Pro is working.

**Comment by gofujita** [comment]
I've updated E/D and it works on macOS 12.0.1., Monteley. I've tried some one line scripts and others with multiple lines on Script menu. They work well.

**Comment by gofujita** [comment]
I can not see my writings and reopen my opml files on E/D. This happened after several hours writing on E/D and closed my MacBook for a while. I could open the file with TextEdit and I see my data were kept there. Rebooting E/D or macOS did not work to fix it. If you have any good advice, please let me know.
<img width="1312" alt="Screen Shot 2021-11-13 at 13 12 29" src="https://user-images.githubusercontent.com/15359297/141605738-b15e7e33-16c3-4026-850f-34ba4a538e91.png">

**Comment by scripting** [comment]
Open the JavaScript console, see if there are any error messages. Post a screen shot here.

**Comment by gofujita** [comment]
I could not find the error message at JS console, but attached a screenshot. After the last message, probably because I restarted E/D several times, the screen has a bit change. The file name in tab became to 'Untitled' (the real name is different), and two new added outline items appeared because I click the Plus icon twice. The data I wrote before is still invisible.

Thank you.

<img width="1552" alt="Screen Shot 2021-11-13 at 16 50 58" src="https://user-images.githubusercontent.com/15359297/141611018-a83b85d7-67ef-4e04-8617-720d7bed8858.png">

**Comment by papascott** [comment]
@gofujita I've seen this behavior (at least one time in Web Drummer) when the outline become corrupted, for example with an extra line with 'ml>' at the end of the file. Trying to open the outline results in a blank tab, and writing in the tab may overwrite the outline. I believe outlines becoming corrupted is a known problem, but happens so seldom that it is very difficult to find the cause and fix.

@scripting I deliberately tried to open a corrupt outline in Electric Dummer and got an "uncaught error" in the console, starting at line 195 of the attached log.

[1636793146595.log](https://github.com/scripting/drummerSupport/files/7531684/1636793146595.log)

**Comment by scripting** [comment]
@papascott — I know you’re trying to help, but we have no idea what’s going on on his computer or what the user did. He’s not giving us any information other than something de did didn’t work.

**Comment by gofujita** [comment]
I'll try to find efficient information by myself to solve the issue. I deeply apologize for asking here without any useful information.

**Comment by scripting** [comment]
@gofujita -- a good place to start is with what's actually in the file on your computer. if you can open it in a text editor, let us know what you see.

**Comment by gofujita** [comment]
@scripting -- Thanks for the advice. I opened the file in a text editor and carefully checked it, all the text I had written earlier was gone, but I couldn't find anything that could have caused the problem. After the error, I restarted and reloaded the file several times, which may have erased the cause of the problem. This may not happen very often, but if I encounter a similar error, I will try to examine the file and JS console immediately. I apologize for the inconvenience.
